apiVersion: v1
kind: ConfigMap
metadata:
  name: azd-env-configmap
data:
  API_ALLOW_ORIGINS: ""
  APPLICATIONINSIGHTS_CONNECTION_STRING: ""
  AZURE_AKS_CLUSTER_NAME: ""
  AZURE_CLIENT_ID: ""
  AZURE_CONTAINER_REGISTRY_ENDPOINT: ""
  AZURE_CONTAINER_REGISTRY_NAME: ""
  AZURE_ENV_NAME: ""
  AZURE_FORMRECOGNIZER_RESOURCE_GROUP: ""
  AZURE_FORMRECOGNIZER_SERVICE: ""
  AZURE_KEY_VAULT_ENDPOINT: ""
  AZURE_LOCATION: ""
  AZURE_OPENAI_CHATGPT_DEPLOYMENT: ""
  AZURE_OPENAI_CHATGPT_MODEL: ""
  AZURE_OPENAI_EMB_DEPLOYMENT: ""
  AZURE_OPENAI_EMB_MODEL_NAME: ""
  AZURE_OPENAI_RESOURCE_GROUP: ""
  AZURE_OPENAI_SERVICE: ""
  AZURE_RESOURCE_GROUP: ""
  AZURE_SEARCH_INDEX: ""
  AZURE_SEARCH_SERVICE: ""
  AZURE_SEARCH_SERVICE_RESOURCE_GROUP: ""
  AZURE_SERVICEBUS_NAMESPACE: ""
  AZURE_SERVICEBUS_SKU_NAME: ""
  AZURE_STORAGE_ACCOUNT: ""
  AZURE_STORAGE_CONTAINER: ""
  AZURE_STORAGE_RESOURCE_GROUP: ""
  AZURE_SUBSCRIPTION_ID: ""
  AZURE_TENANT_ID: ""
  OPENAI_API_KEY: ""
  OPENAI_HOST: ""
  OPENAI_ORGANIZATION: ""
  REACT_APP_APPLICATIONINSIGHTS_CONNECTION_STRING: ""
  SERVICE_API_ENDPOINT_URL: ""
  SERVICE_API_IMAGE_NAME: ""
  SERVICE_FRONTEND_ENDPOINT_URL: ""
  SERVICE_FRONTEND_IMAGE_NAME: ""
  SERVICE_INDEXER_ENDPOINT_URL: ""
  SERVICE_INDEXER_IMAGE_NAME: ""

